### ISSUE TITLE
Need private images and prompts also

### ISSUE THREAD

**Issue by Wammie777** [alexfixer/Playground-backup#1]
I need private images and their prompts. Can you modify the Python script or add new parameter(s) to fetch private images and prompts also?

**Comment by alexfixer** [comment]
Hi. Sorry, that's not possible. If you want to download private images, make them public.

**Comment by Wammie777** [comment]
> Hi. Sorry, that's not possible. If you want to download private images, make them public.

Alright, so thank you for the work you have done and for sharing your script. It worked for me on public images. Much appreciated!
